### ISSUE TITLE
It doesn't work with ServeStaticModule

### ISSUE THREAD

**Issue by pderiy** [Pop-Code/nestjs-console#153]
Hello, I'm using next module:
```typescript
        ServeStaticModule.forRoot({
            rootPath: join(__dirname, '..', 'static_www'),
            renderPath: '/',
            exclude: ['/api*'],
        }),
```
And have next error:

> (node:2065) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getInstance' of null
at ExpressLoader.register (/Users/backend/node_modules/@nestjs/serve-static/dist/loaders/express.loader.js:17:33)
at ServeStaticModule.<anonymous> (/Users/backend/node_modules/@nestjs/serve-static/dist/serve-static.module.js:87:25)
at Generator.next (<anonymous>)
at /Users/backend/node_modules/@nestjs/serve-static/dist/serve-static.module.js:20:71
at new Promise (<anonymous>)
at __awaiter (/Users/backend/node_modules/@nestjs/serve-static/dist/serve-static.module.js:16:12)
at ServeStaticModule.onModuleInit (/Users/backend/node_modules/@nestjs/serve-static/dist/serve-static.module.js:85:16)
at Object.callModuleInitHook (/Users/backend/node_modules/@nestjs/core/hooks/on-module-init.hook.js:50:35)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async NestApplicationContext.callInitHook (/Users/backend/node_modules/@nestjs/core/nest-application-context.js:153:13)
(node:2065) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
    (node:2065) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

After I remove 'ServeStaticModule' everything works fine.

**Comment by Rmannn** [comment]
As explained on the readme, this module is creating a nest application context, headless app. It won't work with a server instance. 
A nest application is required to start a server. The default bootstrap is creating a NestApplicationContext and not a NestApplication.

To make it work, you have to override the create Method of the Bootstrap class to create a nest application instead a headless app. Then use this class to boot the cli in your console.ts file.

**Comment by Rmannn** [comment]
In the 2.0 version a server compatible bootstrap was provided.
You can use it as an exemple to create the good type of instance.
https://github.com/Pop-Code/nestjs-console/blob/v2.0.0/src/bootstrap/server.ts

Fell free to reopen if it does not work as expected.

**Comment by pderiy** [comment]
Yes it works great, thanks.
I extende your class:
![image](https://user-images.githubusercontent.com/9549383/81750135-38b72080-94ad-11ea-9937-41604ac1932c.png)
