### ISSUE TITLE
_actionResults is undefined

### ISSUE THREAD

**Issue by floross** [Pop-Code/nestjs-console#344]
When using this library with the latest version I got this error:

```bash
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.all (<anonymous>)
    at ConsoleService.<anonymous> (/data/Projects/stack/node_modules/nestjs-console/src/service.ts:107:27)
    at Generator.next (<anonymous>)
    at fulfilled (/data/Projects/stack/node_modules/nestjs-console/dist/service.js:17:58)
```

This error is telling that `this.cli._actionResults` is undefined. My handler is correctly executed and this error pop after the execution.
https://github.com/Pop-Code/nestjs-console/blob/1d4309881ab5b2d16e34b2f5f6cd5b5f43159215/src/service.ts#L106

**Comment by Rmannn** [comment]
fixed in nestjs-console@7.0.0
The module was updated to support lastest commander version 8.1.0
