### ISSUE TITLE
Unable to register commands in nestjs-console

### ISSUE THREAD

**Issue by mohsinamjad** [Pop-Code/nestjs-console#357]
I'm following the wiki guide, trying to configure it in nestjs monorepo mode with version `7.6.15`

STEP1 
```
// console.ts - example of entrypoint
import { BootstrapConsole } from 'nestjs-console';
import { AppModule } from './app.module';

const bootstrap = new BootstrapConsole({
  module: AppModule,
  useDecorators: true,
});
bootstrap.init().then(async (app) => {
  try {
    await app.init();
    await bootstrap.boot();
    await app.close();
  } catch (e) {
    console.error(e);
    await app.close();
    process.exit(1);
  }
});
```

STEP2
```
// in app.module
@Module({
  imports: [
    ConsoleModule,
   ...
   ...
   providers: [ CLIProvider ]
```

STEP3 command
```
@Console()
export class CLIProvider {
  @Command({
    command: 'list <directory>',
    description: 'List content of a directory',
  })
  async listContent(directory: string): Promise<void> {
    // See Ora npm package for details about spinner
    const spin = createSpinner();
    spin.start(`Listing files in directory ${directory}`);

    // simulate a long task of 1 seconds
    const files = await new Promise((done) =>
      setTimeout(() => done(['fileA', 'fileB']), 1000),
    );

    spin.succeed('Listing done');

    // send the response to the  cli
    // you could also use process.stdout.write()
    console.log(JSON.stringify(files));
  }
}

```
After running this command `npx ts-node -r tsconfig-paths/register apps/scratch/src/console.ts --help ` I get this wierd error which is not helpful.
```
(node:9784) UnhandledPromiseRejectionWarning: Error: Nest could not find given element (this provider does not exist in the current context)
    at InstanceLinksHost.get (/home/in01-nbk-741/Work/extras/nest/scratch/node_modules/@nestjs/core/injector/instance-links-host.js:18:19)
    at NestApplicationContext.resolvePerContext (/home/in01-nbk-741/Work/extras/nest/scratch/node_modules/@nestjs/core/nest-application-context.js:222:38)
    at NestApplicationContext.resolve (/home/in01-nbk-741/Work/extras/nest/scratch/node_modules/@nestjs/core/nest-application-context.js:59:21)
    at ConsoleScanner.<anonymous> (/home/in01-nbk-741/Work/extras/nest/scratch/node_modules/nestjs-console/src/scanner.ts:85:52)
    at Generator.next (<anonymous>)
    at /home/in01-nbk-741/Work/extras/nest/scratch/node_modules/nestjs-console/dist/scanner.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/in01-nbk-741/Work/extras/nest/scratch/node_modules/nestjs-console/dist/scanner.js:4:12)
    at /home/in01-nbk-741/Work/extras/nest/scratch/node_modules/nestjs-console/src/scanner.ts:63:106
    at Array.map (<anonymous>)
(node:9784) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:9784) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Rmannn** [comment]
For nestjs 7 please use nestjs-console@5.0.1 https://www.npmjs.com/package/nestjs-console/v/5.0.1

*wiki here https://github.com/Pop-Code/nestjs-console/wiki/Install-from-npm*

**Comment by mohsinamjad** [comment]
@Rmannn I'm already using the latest verstion `7.0.0` ?

**Comment by Rmannn** [comment]
The last version is only supporting nestjs 8, nestjs console 5.0.0 is compatible with netjs 7.

**Comment by mohsinamjad** [comment]
Got it, after downgrading it `5.0.1`, it started working,
also I have to downgrade commander to `7.2.0` otherwise it was throwing this error
https://github.com/Pop-Code/nestjs-console/issues/344

Thanks for this awesome nest wrapper on commander.
Hope it works well with nestjs DI.
