### ISSUE TITLE
CLI will _always_ throw an error even with empty promise handler

### ISSUE THREAD

**Issue by hbina** [Pop-Code/nestjs-console#359]
```bash
bash-3.2$ npm run console:dev -- list-negative-layers

> <omitted>@<omitted> console:dev
> ts-node -r tsconfig-paths/register src/console.ts "<omitted>"

<omitted>
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.all (<anonymous>)
    at ConsoleService.<anonymous> (/Users/hbina/<omitted>/node_modules/nestjs-console/src/service.ts:106:39)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/hbina/<omitted>/node_modules/nestjs-console/dist/service.js:17:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
bash-3.2$ npm ls nestjs-console
@<omitted>@<omitted> /Users/hbina/<omitted>
└── nestjs-console@5.0.1

bash-3.2$ npm --version
7.21.0
```

**Comment by Rmannn** [comment]
any news here ?

**Comment by hbina** [comment]
Seems to be an issue with missing peer dependency. I simply needed to installed `commander` of the appropriate version.
